"""Cover letter generator for Web3 jobs."""

COVER_LETTER_TEMPLATE = """Subject: Application for {title} at {company}

Dear Hiring Manager,

I am writing to express my interest in the {title} position at {company}.

BACKGROUND
I am a blockchain developer with expertise in {skills}. I have hands-on experience
building and deploying smart contracts, with a focus on security and gas optimization.

RELEVANT EXPERIENCE
- Built and deployed 4 smart contracts on Base Sepolia (ERC-20, Agent Registry, Payment Channel, Marketplace)
- Wrote 141+ tests (87 Solidity, 54 Rust, 16 Node) — all passing
- Passed Slither and Mythril security audits with zero critical findings
- Built a TypeScript SDK with viem and a Rust L1 node with Substrate
- Implemented Dilithium3 post-quantum signatures (NIST FIPS 204)

WHY {company}
{company} is at the forefront of the Web3 revolution. I am particularly
impressed by {specific_project}. My experience in {relevant_skill} aligns
perfectly with your team's needs.

I am available for a technical interview at your convenience. I can share my
GitHub profile and live testnet deployments for review.

Best regards,
[Your Name]
GitHub: github.com/yourusername
Twitter: @yourhandle

---
Generated by web3-gig-finder CLI
"""


def generate_cover_letter(
    title: str,
    company: str,
    skills: list[str],
    specific_project: str = "your innovative approach to Web3",
    relevant_skill: str = "blockchain development",
) -> str:
    """Generate a cover letter template."""
    return COVER_LETTER_TEMPLATE.format(
        title=title,
        company=company,
        skills=", ".join(skills),
        specific_project=specific_project,
        relevant_skill=relevant_skill,
    )
