"""Sample job data — in production, scrape from real platforms."""

SAMPLE_JOBS = [
    # === SOLIDITY / SMART CONTRACTS ===
    {
        "title": "Senior Solidity Developer",
        "company": "Aave",
        "platform": "remote",
        "skills": ["solidity", "defi", "eth"],
        "rate": "$120-180/hr",
        "rate_num": 150,
        "type": "freelance",
        "url": "https://aave.com/careers",
        "description": "Build DeFi lending protocols. Experience with Aave v3 required.",
    },
    {
        "title": "Smart Contract Auditor",
        "company": "OpenZeppelin",
        "platform": "toptal",
        "skills": ["solidity", "security", "audit"],
        "rate": "$150-250/hr",
        "rate_num": 200,
        "type": "freelance",
        "url": "https://openzeppelin.com/careers",
        "description": "Audit smart contracts for vulnerabilities. Slither/Mythril experience.",
    },
    {
        "title": "Solidity Engineer",
        "company": "Uniswap",
        "platform": "remote",
        "skills": ["solidity", "defi", "typescript"],
        "rate": "$140-200/hr",
        "rate_num": 170,
        "type": "freelance",
        "url": "https://uniswap.org/careers",
        "description": "Build DEX features. Deep knowledge of AMMs and liquidity pools.",
    },
    {
        "title": "DeFi Protocol Developer",
        "company": "Compound",
        "platform": "remote",
        "skills": ["solidity", "defi", "python"],
        "rate": "$130-190/hr",
        "rate_num": 160,
        "type": "freelance",
        "url": "https://compound.finance",
        "description": "Build lending/borrowing protocols. Compound v3 experience.",
    },
    {
        "title": "ERC-4626 Vault Developer",
        "company": "Yearn Finance",
        "platform": "remote",
        "skills": ["solidity", "defi", "vaults"],
        "rate": "$110-160/hr",
        "rate_num": 135,
        "type": "freelance",
        "url": "https://yearn.finance",
        "description": "Build yield vaults. ERC-4626 standard expertise.",
    },

    # === RUST / BLOCKCHAIN ===
    {
        "title": "Rust Blockchain Developer",
        "company": "Solana Foundation",
        "platform": "remote",
        "skills": ["rust", "blockchain", "solana"],
        "rate": "$130-200/hr",
        "rate_num": 165,
        "type": "freelance",
        "url": "https://solana.com",
        "description": "Build on Solana. Rust + Anchor framework experience.",
    },
    {
        "title": "Substrate Developer",
        "company": "Parity",
        "platform": "remote",
        "skills": ["rust", "substrate", "blockchain"],
        "rate": "$120-180/hr",
        "rate_num": 150,
        "type": "freelance",
        "url": "https://parity.io",
        "description": "Build custom blockchains with Substrate. Rust expertise required.",
    },
    {
        "title": "Rust Cryptography Engineer",
        "company": "Zcash Foundation",
        "platform": "remote",
        "skills": ["rust", "cryptography", "zkp"],
        "rate": "$140-220/hr",
        "rate_num": 180,
        "type": "freelance",
        "url": "https://z.cash",
        "description": "Implement post-quantum cryptography in Rust. Dilithium/Kyber experience.",
    },
    {
        "title": "Cosmos SDK Developer",
        "company": "Cosmos",
        "platform": "remote",
        "skills": ["rust", "go", "cosmos"],
        "rate": "$110-170/hr",
        "rate_num": 140,
        "type": "freelance",
        "url": "https://cosmos.network",
        "description": "Build Cosmos SDK modules. Go/Rust experience required.",
    },
    {
        "title": "Polkadot Parachain Developer",
        "company": "Web3 Foundation",
        "platform": "remote",
        "skills": ["rust", "substrate", "polkadot"],
        "rate": "$120-190/hr",
        "rate_num": 155,
        "type": "freelance",
        "url": "https://web3.foundation",
        "description": "Build parachains for Polkadot ecosystem.",
    },

    # === TYPESCRIPT / WEB3 ===
    {
        "title": "Web3 Frontend Developer",
        "company": "ENS",
        "platform": "remote",
        "skills": ["typescript", "react", "web3"],
        "rate": "$80-130/hr",
        "rate_num": 105,
        "type": "freelance",
        "url": "https://ens.domains",
        "description": "Build ENS dApp frontend. React + viem/wagmi.",
    },
    {
        "title": "DApp Developer",
        "company": "Lens Protocol",
        "platform": "remote",
        "skills": ["typescript", "react", "web3"],
        "rate": "$90-140/hr",
        "rate_num": 115,
        "type": "freelance",
        "url": "https://lens.xyz",
        "description": "Build social dApps on Lens Protocol.",
    },
    {
        "title": "Smart Contract SDK Developer",
        "company": "Alchemy",
        "platform": "remote",
        "skills": ["typescript", "eth", "sdk"],
        "rate": "$100-150/hr",
        "rate_num": 125,
        "type": "freelance",
        "url": "https://alchemy.com",
        "description": "Build Web3 SDKs and developer tools.",
    },
    {
        "title": "NFT Marketplace Developer",
        "company": "OpenSea",
        "platform": "remote",
        "skills": ["typescript", "solidity", "nft"],
        "rate": "$90-140/hr",
        "rate_num": 115,
        "type": "freelance",
        "url": "https://opensea.io",
        "description": "Build NFT marketplace features. Solidity + React.",
    },
    {
        "title": "Cross-Chain Bridge Developer",
        "company": "LayerZero",
        "platform": "remote",
        "skills": ["typescript", "solidity", "bridge"],
        "rate": "$110-160/hr",
        "rate_num": 135,
        "type": "freelance",
        "url": "https://layerzero.network",
        "description": "Build cross-chain messaging protocol.",
    },

    # === AI + WEB3 ===
    {
        "title": "AI Agent Developer",
        "company": "Fetch.ai",
        "platform": "remote",
        "skills": ["python", "ai", "web3"],
        "rate": "$100-160/hr",
        "rate_num": 130,
        "type": "freelance",
        "url": "https://fetch.ai",
        "description": "Build autonomous AI agents on blockchain.",
    },
    {
        "title": "ML Engineer (Crypto)",
        "company": "Chainalysis",
        "platform": "remote",
        "skills": ["python", "ml", "blockchain"],
        "rate": "$120-180/hr",
        "rate_num": 150,
        "type": "freelance",
        "url": "https://chainalysis.com",
        "description": "Build ML models for blockchain analytics.",
    },
    {
        "title": "ZKML Developer",
        "company": "Modulus Labs",
        "platform": "remote",
        "skills": ["python", "zkp", "ml"],
        "rate": "$130-200/hr",
        "rate_num": 165,
        "type": "freelance",
        "url": "https://moduluslabs.xyz",
        "description": "Build zero-knowledge ML proofs. ezkl/Circom experience.",
    },

    # === SECURITY / AUDIT ===
    {
        "title": "Smart Contract Auditor",
        "company": "Trail of Bits",
        "platform": "remote",
        "skills": ["solidity", "security", "audit"],
        "rate": "$180-280/hr",
        "rate_num": 230,
        "type": "freelance",
        "url": "https://trailofbits.com",
        "description": "Audit smart contracts for enterprises. Top-tier security skills.",
    },
    {
        "title": "DeFi Security Researcher",
        "company": "Consensys Diligence",
        "platform": "remote",
        "skills": ["solidity", "security", "defi"],
        "rate": "$150-230/hr",
        "rate_num": 190,
        "type": "freelance",
        "url": "https://consensys.io/diligence",
        "description": "DeFi protocol security reviews.",
    },

    # === MOBILE / MULTICHAIN ===
    {
        "title": "Flutter Web3 Wallet Developer",
        "company": "Rainbow",
        "platform": "remote",
        "skills": ["flutter", "dart", "web3"],
        "rate": "$80-120/hr",
        "rate_num": 100,
        "type": "freelance",
        "url": "https://rainbow.me",
        "description": "Build crypto wallet mobile app. Flutter + Web3.",
    },
    {
        "title": "iOS Crypto Wallet Developer",
        "company": "MetaMask",
        "platform": "remote",
        "skills": ["swift", "ios", "web3"],
        "rate": "$90-140/hr",
        "rate_num": 115,
        "type": "freelance",
        "url": "https://metamask.io",
        "description": "Build MetaMask iOS features. Swift + Web3.",
    },

    # === DEVOPS / INFRA ===
    {
        "title": "Blockchain DevOps Engineer",
        "company": "Infura",
        "platform": "remote",
        "skills": ["devops", "kubernetes", "blockchain"],
        "rate": "$100-150/hr",
        "rate_num": 125,
        "type": "freelance",
        "url": "https://infura.io",
        "description": "Manage blockchain node infrastructure.",
    },
    {
        "title": "Node Operator",
        "company": "Figment",
        "platform": "remote",
        "skills": ["devops", "linux", "blockchain"],
        "rate": "$80-120/hr",
        "rate_num": 100,
        "type": "freelance",
        "url": "https://figment.io",
        "description": "Run and maintain blockchain validator nodes.",
    },
]

SAMPLE_GRANTS = [
    {
        "name": "Base Builder Grant",
        "amount": "$5,000 - $25,000",
        "url": "https://base.org/builders",
        "deadline": "Rolling",
        "requirements": "Build on Base L2",
    },
    {
        "name": "Optimism RetroPGF",
        "amount": "Varies (community voted)",
        "url": "https://optimism.io/retroPGF",
        "deadline": "Quarterly rounds",
        "requirements": "Contribute to Optimism ecosystem",
    },
    {
        "name": "Arbitrum DAO Grants",
        "amount": "$5,000 - $50,000",
        "url": "https://arbitrum.io",
        "deadline": "Rolling",
        "requirements": "Build on Arbitrum",
    },
    {
        "name": "Gitcoin Grants",
        "amount": "$1,000 - $100,000",
        "url": "https://gitcoin.co/grants",
        "deadline": "Quarterly rounds",
        "requirements": "Open source public goods",
    },
    {
        "name": "Ethereum Foundation Grants",
        "amount": "$10,000 - $100,000+",
        "url": "https://ethereum.org/en/community/grants/",
        "deadline": "Rolling",
        "requirements": "Advance Ethereum ecosystem",
    },
    {
        "name": "Protocol Labs Grants",
        "amount": "$5,000 - $50,000",
        "url": "https://protocol.ai",
        "deadline": "Rolling",
        "requirements": "IPFS/Filecoin/libp2p",
    },
    {
        "name": "Solana Foundation Grants",
        "amount": "$10,000 - $100,000",
        "url": "https://solana.com/grants",
        "deadline": "Rolling",
        "requirements": "Build on Solana",
    },
    {
        "name": "Polkadot Treasury",
        "amount": "$10,000 - $500,000",
        "url": "https://polkadot.network",
        "deadline": "Governance vote",
        "requirements": "Contribute to Polkadot",
    },
]

SAMPLE_AUDITS = [
    {
        "name": "Code4rena Active Contest",
        "prize": "$50,000 - $500,000",
        "url": "https://code4rena.com",
        "duration": "5-7 days",
        "skills": ["solidity", "security"],
    },
    {
        "name": "Sherlock Audit Contest",
        "prize": "$20,000 - $200,000",
        "url": "https://sherlock.xyz",
        "duration": "5-14 days",
        "skills": ["solidity", "security"],
    },
    {
        "name": "Immunefi Bug Bounties",
        "prize": "$1,000 - $10,000,000",
        "url": "https://immunefi.com",
        "duration": "Ongoing",
        "skills": ["solidity", "security", "defi"],
    },
    {
        "name": "Hats.finance Contests",
        "prize": "$10,000 - $100,000",
        "url": "https://hats.finance",
        "duration": "7 days",
        "skills": ["solidity", "security"],
    },
]
